# Generated by Django 4.1.7 on 2023-05-24 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
from ..models import Status


def reinit_all_instances(apps, schema_editor):
    for name, _ in Status.name_options:
        Status.objects.create(name=name)


def remove_all_instances(apps, schema_editor):
    Status.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    choices=[('free', 'free'), ('assigned', 'assigned'),
                             ('under_construction', 'under_construction'),
                             ('completed', 'completed')], default='free',
                    max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True,
                                              db_index=True,
                                              verbose_name='ID')),
                ('name', models.CharField(
                    choices=[('free', 'free'), ('assigned', 'assigned'),
                             ('under_construction', 'under_construction'),
                             ('completed', 'completed')], db_index=True,
                    default='free', max_length=200)),
                ('history_id',
                 models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason',
                 models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(
                    choices=[('+', 'Created'), ('~', 'Changed'),
                             ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True,
                                                   on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='+',
                                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical status',
                'verbose_name_plural': 'historical statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(
            code=reinit_all_instances,
            reverse_code=remove_all_instances,
        ),
    ]
