# Generated by Django 5.0.1 on 2024-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatus',
            name='name',
            field=models.CharField(choices=[('free', 'free'), ('assigned', 'assigned'), ('under_construction', 'under_construction'), ('completed', 'completed'), ('for_event', 'for_event'), ('for_event_done', 'for_event_done')], db_index=True, default='free', max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('free', 'free'), ('assigned', 'assigned'), ('under_construction', 'under_construction'), ('completed', 'completed'), ('for_event', 'for_event'), ('for_event_done', 'for_event_done')], default='free', max_length=200, unique=True),
        ),
    ]
