# Generated by Django 4.1.7 on 2023-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_reinit_all_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstatus',
            name='name',
            field=models.CharField(choices=[('free', 'free'), ('assigned', 'assigned'), ('under_construction', 'under_construction'), ('completed', 'completed')], db_index=True, default='free', max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('free', 'free'), ('assigned', 'assigned'), ('under_construction', 'under_construction'), ('completed', 'completed')], default='free', max_length=200, unique=True),
        ),
    ]
