version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: Docker/sectors/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - media:/app/media/:rw
            - ./app/territory_sectors:/app/teritory_sectors
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgis/Dockerfile
        env_file:
            -   ./Docker/postgis/env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - media:/app/media/:rw
        ports:
            - 80:80
        depends_on:
            - sectors

volumes:
    pgdata:
    media:
