version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: ./Docker/sectors/Dockerfile
        env_file:
            - .env-compose
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgis/Dockerfile
        env_file:
            -   ./Docker/postgis/env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
            args:
                CERTBOT_DOMAINS: ${CERTBOT_DOMAINS}
        env_file:
            - .env-compose
        volumes:
            - letsencrypt:/etc/letsencrypt/:ro
            - acme:/var/www/letsencrypt:ro
            - nginx-conf:/etc/nginx/conf.d
        ports:
            - 80:80
        depends_on:
            - sectors
    certbot:
        build:
            context: .
            dockerfile: ./Docker/certbot/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - letsencrypt:/etc/letsencrypt/
            - acme:/var/www/letsencrypt/
            - nginx-conf:/nginx/
        depends_on:
            - nginx

volumes:
    pgdata:
    letsencrypt:
    acme:
    nginx-conf: