version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: Docker/sectors/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - app:/app/
        expose:
            - 8000
        entrypoint: ./docker-entrypoint.sh
        depends_on:
            - pgdatabase

    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgis/Dockerfile
        env_file:
            -   ./Docker/postgis/env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - app:/app/:rw
        ports:
            - 80:80
        depends_on:
            - sectors

volumes:
    pgdata:
    app:
        driver: local
        driver_opts:
            type: none
            device: ./app
            o: bind