version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: ./Docker/sectors/Dockerfile
        env_file:
            - .env-compose
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgis/Dockerfile
        env_file:
            -   ./Docker/postgis/env
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        volumes:
            - letsencrypt:/etc/letsencrypt/:ro
            - ./letsencrypt/www:/var/www/letsencrypt:ro
        ports:
            - 80:80
        depends_on:
            - sectors
            - certbot
    certbot:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        volumes:
            - letsencrypt:/etc/letsencrypt
            - ./letsencrypt/www:/var/www/letsencrypt
        command: certonly --webroot --agree-tos --non-interactive --email you@example.com --webroot-path /var/www/letsencrypt

volumes:
    pgdata:
    letsencrypt:

