version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: Docker/sectors/Dockerfile
        env_file:
            - .env-compose
        environment:
            - DOCKER_DB_HOST=pgdatabase
        volumes:
            - ./app:/app/
            - ./log:/var/log/:rw
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        image: "postgis/postgis:latest"
        env_file:
            - .env-compose
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
            - ./log:/var/log/:rw
    nginx:
        env_file:
            - .env-compose
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        environment:
            - CERTBOT_DOMAINS=${CERTBOT_DOMAINS}
        volumes:
            - letsencrypt:/etc/letsencrypt/:ro
            - acme:/var/www/letsencrypt/:ro
            - nginx-conf:/etc/nginx/conf.d/:rw
            - ./app/media:/app/media/:rw
            - ./log:/var/log/:rw
        ports:
            - 80:80
            - 443:443
        depends_on:
            - sectors
    certbot:
        build:
            context: .
            dockerfile: ./Docker/certbot/Dockerfile
        env_file:
            - .env-compose
        volumes:
            - letsencrypt:/etc/letsencrypt/:rw
            - acme:/var/www/letsencrypt/:rw
            - nginx-conf:/nginx/:rw
            - ./log:/var/log/:rw
        depends_on:
            - nginx

volumes:
    pgdata:
    letsencrypt:
    acme:
    nginx-conf:
    log: