version: "3.9"

services:
    sectors:
        build:
            context: .
            dockerfile: ./Docker/sectors/Dockerfile
        env_file:
            - .env
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        build:
            context: .
            dockerfile: ./Docker/postgis/Dockerfile
        environment:
            - POSTGRES_USER=sectors
            - POSTGRES_PASSWORD=sectors
            - POSTGRES_DB=sectors
            - DJANGO_SUPERUSER_PASSWORD = sectors
            - DJANGO_SUPERUSER_EMAIL = sectors@secorssec
            - DJANGO_SUPERUSER_USERNAME = sectors
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - sectors
volumes:
    pgdata:
