version: "3.9"

services:
    sectors:
        build:
            - dockerfile: ./Docker/sectors
        env_file:
            - .env
        expose:
            - 8000
        depends_on:
            - pgdatabase

    pgdatabase:
        image: postgis/postgis:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw
    nginx:
        build:
            - dockerfile: ./Docker/nginx
        ports:
            - 80:80
        depends_on:
            - sectors
volumes:
    pgdata:
