# Generated by Django 4.1.5 on 2023-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_historicalhouse_address_alter_house_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhouse',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sector',
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='desc',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='house',
            name='desc',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
