# Generated by Django 4.1.5 on 2023-02-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_house_options_alter_house_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='house',
            managers=[
            ],
        ),
    ]
