# Generated by Django 4.1.7 on 2023-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_alter_house_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouse',
            name='tech_desc',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='tech_desc',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
