# Generated by Django 4.1.5 on 2023-01-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
