# Generated by Django 4.1.5 on 2023-01-15 08:58

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0002_sector_name'),
        ('flat', '0004_flat_entrance'),
        ('house', '0006_house_entrances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uuid',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, auto_created=True, length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flat.flat')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.house')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.sector')),
            ],
        ),
    ]
