# Generated by Django 4.1.7 on 2023-03-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed',
            field=models.BooleanField(default=False, help_text='check if task is completed.Uncheck, if task need to improve'),
        ),
    ]
