# Generated by Django 4.1.7 on 2023-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0005_alter_sector_options_historicalsector_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsector',
            name='for_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sector',
            name='for_search',
            field=models.BooleanField(default=False),
        ),
    ]
