# Generated by Django 4.1.7 on 2023-04-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0006_historicalsector_for_search_sector_for_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('name',)},
        ),
    ]
