# Generated by Django 4.1.7 on 2023-03-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_alter_historicallanguage_name_alter_language_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('id',)},
        ),
    ]
