# Generated by Django 4.1.5 on 2023-01-18 10:00

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Polygon



class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='contour',
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=Polygon(
                    (
                        (41.611895, 41.632995),
                        (41.61150481083692, 41.6326204812093),
                        (41.612636703041005, 41.632195475651),
                        (41.611895, 41.632995)
                    )
                ),
                srid=4326
            ),
            preserve_default=False,
        ),
    ]
