# Generated by Django 4.1.5 on 2023-01-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
