# Generated by Django 4.1.5 on 2023-02-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0005_alter_sector_options_historicalsector_assigned_to_and_more'),
        ('sector', '0005_status_sectorstatus'),
    ]

    operations = [
    ]
