# Generated by Django 4.1.5 on 2023-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_historicallanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallanguage',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
