# Generated by Django 4.1.7 on 2023-04-06 13:30

from django.db import migrations

from territory_sectors.status.models import Status


def reinit_all_instances(apps, schema_editor):
    Status.objects.all().delete()
    for name, _ in Status.name_options:
        Status.objects.create(name=name)

def remove_all_instances(apps, schema_editor):
    Status.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=reinit_all_instances,
            reverse_code=remove_all_instances,
        ),

    ]
