# Generated by Django 4.1.5 on 2023-01-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='house',
            new_name='sector',
        ),
        migrations.AddField(
            model_name='house',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
