# Generated by Django 4.1.5 on 2023-01-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_house_house_sector_house_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='floor',
            new_name='floor_amount',
        ),
    ]
