# Generated by Django 4.1.5 on 2023-01-13 09:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_rename_floor_house_floor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='gps_point',
            field=django.contrib.gis.db.models.fields.PointField(default=(0.0, 0.0), srid=4326),
            preserve_default=False,
        ),
    ]
