# Generated by Django 4.1.5 on 2023-02-12 04:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_historicalhouse_desc_alter_house_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelManagers(
            name='house',
            managers=[
                ('flats_json', django.db.models.manager.Manager()),
            ],
        ),
    ]
