# Generated by Django 4.1.5 on 2023-02-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_house_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={},
        ),
    ]
