# Generated by Django 4.1.7 on 2023-03-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_alter_house_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouse',
            name='for_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='for_search',
            field=models.BooleanField(default=True),
        ),
    ]
