# Generated by Django 4.1.5 on 2023-01-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('house', '0002_alter_house_house'),
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='language.language'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.house'),
        ),
    ]
