# Generated by Django 4.1.5 on 2023-01-13 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_house_house_sector_house_floor'),
        ('flat', '0002_flat_language_alter_flat_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
