# Generated by Django 4.1.5 on 2023-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_historicalflat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='way_desc',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='historicalflat',
            name='way_desc',
            field=models.CharField(max_length=1500),
        ),
    ]
