# Generated by Django 4.1.5 on 2023-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_alter_flat_floor_alter_flat_house_alter_flat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
