# Generated by Django 4.1.5 on 2023-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_historicalhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouse',
            name='address',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
