# Generated by Django 4.1.7 on 2023-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_alter_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhouse',
            name='image_preview',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
    ]
