# Generated by Django 4.1.7 on 2023-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_historicalhouse_image_preview_house_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='house/preview/'),
        ),
    ]
