# Generated by Django 4.1.7 on 2023-05-17 13:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uuid_qr', '0001_initial'),
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
                ('for_search', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=300, null=True)),
                ('contour', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.status')),
                ('uuid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uuid_qr.uuid')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSector',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_joined', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(db_index=True, max_length=300, null=True)),
                ('for_search', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=300, null=True)),
                ('contour', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='status.status')),
                ('uuid', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uuid_qr.uuid')),
            ],
            options={
                'verbose_name': 'historical sector',
                'verbose_name_plural': 'historical sectors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
