# Generated by Django 4.1.7 on 2023-06-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsector',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='historical', to='sector.sector'),
            preserve_default=False,
        ),
    ]
