# Generated by Django 4.1.7 on 2023-05-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0007_alter_sector_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
    ]
