FROM certbot/certbot

RUN mkdir -p /var/www/letsencrypt

#ENTRYPOINT [ "certbot", "certonly", "--webroot", "--agree-tos", "--non-interactive", "--email", "you@example.com", "--webroot-path", "/var/www/letsencrypt" ]
