# Generated by Django 4.1.5 on 2023-01-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        ('language', '0001_initial'),
        ('uuid_qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('entrance', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('way_desc', models.CharField(max_length=500)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='language.language')),
                ('uuid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uuid_qr.uuid')),
            ],
        ),
    ]
