# Generated by Django 4.1.7 on 2023-05-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
        ('house', '0001_initial'),
        ('uuid_qr', '0001_initial'),
        ('language', '0004_alter_language_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalflat',
            name='house',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='house.house'),
        ),
        migrations.AddField(
            model_name='historicalflat',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='language.language'),
        ),
        migrations.AddField(
            model_name='historicalflat',
            name='uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uuid_qr.uuid'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
        migrations.AddField(
            model_name='flat',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='language.language'),
        ),
        migrations.AddField(
            model_name='flat',
            name='uuid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uuid_qr.uuid'),
        ),
    ]
