# Generated by Django 4.1.5 on 2023-02-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_alter_flat_way_desc_alter_historicalflat_way_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['house', 'entrance', 'floor', 'number']},
        ),
    ]
