name: codeclimate-coverage
on: push
env:
  DEBUG: 'True'
  DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test
  DOCKER_DB_HOST: localhost
  GDAL_LIBRARY_PATH: /usr/lib/libgdal.so
jobs:
  my-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
          pip install coverage
      - name: Install GDAL
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
          sudo apt-get update -q
          sudo apt-get install gdal-bin libgdal-dev -y
      - name: run test coverage calculating
        run: |
          make coverage
      - name: publishing info
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.COV }}
        with:
          coverageCommand: make coverage
          workingDirectory: ./app
          debug: true
