name: test
on: push
env:
  SECRET_KEY: ${{ secrets.DJANGO_SECRET }}
  DATABASE_URL: 'postgis://postgres:postgres@postgis:${{ my-job.services.postgis.ports[5432] }}/postgres'
jobs:
  my-job:
    services:
      postgis:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install poetry
              make install
        - name: run tests
          run: |
              make test