name: test
on: push
env:
  DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
  DATABASE_URL: 'postgis://postgres:postgres@localhost:5432/postgres'
  CPLUS_INCLUDE_PATH: '/usr/include/gdal'
  C_INCLUDE_PATH: '/usr/include/gdal'
  DEBUG: 'True'
jobs:
  my-job:
    services:
      postgis:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install poetry
              sudo apt-get install -y libgdal-dev g++ --no-install-recommends
              pip install pipenv
              make install
        - name: run tests
          run: |
              cd app
              mkdir -p staticfiles
              make test